name: 🕷️ Bug Report
description: Report errors or unexpected behavior
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Please search existing issues before submitting a bug.
    - type: textarea
      id: expected-behavior
      attributes:
          label: ✔️ Expected Behavior
          placeholder: What were you expecting?
      validations:
          required: true
    - type: textarea
      id: what-happened
      attributes:
          label: ❌ Actual Behavior
          placeholder: What happened instead?
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: Steps to reproduce
          placeholder: Detailed steps to help reproduce the bug.
      validations:
          required: true
    - type: dropdown
      id: environment
      attributes:
          label: What environment was this in?
          options:
              - Production
              - Closed Beta
              - Dev
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Relevant console log
          description: Provide console log if applicable
          render: shell
    - type: textarea
      attributes:
          label: Extra comments
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
