name: 🔘 Other
description: Used for if its not a feature/issue
labels: ["other"]
body:
    - type: markdown
      attributes:
          value: |
              Please search existing list before submitting.
    - type: textarea
      id: change
      attributes:
          label: Proposed change?
          description: A clear and concise description of what the change is.
      validations:
          required: true
    - type: textarea
      id: purpose
      attributes:
          label: Purpose?
          description: What is the expected outcome.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Extra comments
          description: This can include extra information.
      validations:
          required: false